In [2]:
import pandas as pd

In [3]:
data = {'Classe': ['Júnior', 'Júnior', 'Pleno', 'Pleno', 'Sênior', 'Sênior'],
        'Nome': ['Alice', 'Bob', 'Charlie', 'David','Gabriel','Heloisa'],
        'Venda': [200,120,340,124,243,350]}

df= pd.DataFrame(data)

In [4]:
df

   Classe     Nome  Venda
0  Júnior    Alice    200
1  Júnior      Bob    120
2   Pleno  Charlie    340
3   Pleno    David    124
4  Sênior  Gabriel    243
5  Sênior  Heloisa    350

In [5]:
experiencia = df.groupby("Classe")

In [6]:
experiencia.sum()

                  Nome  Venda
Classe
Júnior        AliceBob    320
Pleno     CharlieDavid    464
Sênior  GabrielHeloisa    593

In [7]:
df.groupby('Classe').sum()

                  Nome  Venda
Classe
Júnior        AliceBob    320
Pleno     CharlieDavid    464
Sênior  GabrielHeloisa    593

In [8]:
df.groupby('Classe').max()

           Nome  Venda
Classe
Júnior      Bob    200
Pleno     David    340
Sênior  Heloisa    350

In [ ]:
df.query("Classe == 'Júnior' and Venda > 100")

Empty DataFrame
Columns: [Classe, Nome, Venda]
Index: []